### PR TITLE
fix(gv-button): show loading on button without icon

### LINKED ISSUE #229: gv-button : spinner wheel not displayed on button unless button has icon
As you can see here, only button having icons have the spinning wheel displayed when loading : https://components.gravitee.io/?path=/story/atoms-gv-button--loading

### PR DESCRIPTION
**Pull request by loriepisicchio**
Closes #229

### CODE REVIEW

File: src/atoms/gv-button.js [hunk 1]
```diff
@@ -331,7 +331,7 @@ export class GvButton extends LitElement {
       default: !this.primary && !this.danger && !this.link,
       outlined: this.outlined,
       icon: this.icon || this.iconRight,
-      iconLeft: this.icon,
+      iconLeft: (this.icon || this.loading) && !this.iconRight,
```
Comment (aelamrani) [inline src/atoms/gv-button.js:334]:
```suggestion
      iconLeft: this._getIconLeft(),
```
